[build]
  functions = "netlify/functions"

[functions]
  # Specify any external Node.js modules if needed
  external_node_modules = []

  # Schedule for the function to run at 9:30 AM ET (2:30 PM UTC) on weekdays
  [[functions.scheduled_fetch_stock_data]]
  schedule = "30 14 * * 1-5"

  # Schedule for the function to run at 4:00 PM ET (9:00 PM UTC) on weekdays
  [[functions.scheduled_fetch_stock_data]]
  schedule = "0 21 * * 1-5"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200