[build]
  command = "pip install -r requirements.txt"
  functions = "netlify/functions"

[functions]
  directory = "netlify/functions"
  # Specify any external Node.js modules if needed
  external_node_modules = []

  # Configuration for the scheduled_fetch_stock_data function at 9:30 AM ET (2:30 PM UTC) on weekdays
  [functions.scheduled_fetch_stock_data_open]
  schedule = "30 14 * * 1-5"

  # Configuration for the scheduled_fetch_stock_data function at 4:00 PM ET (9:00 PM UTC) on weekdays
  [functions.scheduled_fetch_stock_data_close]
  schedule = "0 21 * * 1-5"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200